version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://analavishnu4_db_user:10dNfPgk8YQiGIqI@krishna.6yy2ndb.mongodb.net/cms_db?appName=krishna
      - JWT_SECRET=supersecretjwtkey
      - NODE_ENV=development

